# Uncomment the next line to define a global platform for your project
 platform :ios, '15.0'

target 'MarketplaceListing' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MarketplaceListing
  pod 'SwiftLint', '0.57.1'
  pod 'SwiftFormat/CLI', '0.55.3'
  pod 'RxSwift', '6.8.0'
#  pod 'RxCocoa', '6.8.0'
  pod 'Alamofire', '5.10.2'
  
  target 'MarketplaceListingTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '6.8.0'
    pod 'RxTest', '6.8.0'
  end

  target 'MarketplaceListingUITests' do
    # Pods for testing
  end

end
